name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

defaults:
  run:
    shell: bash
    working-directory: "."

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-ui:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: Build UI
      run: docker run --rm -v $(pwd):/src --entrypoint /src/ui-patch/build.sh node:lts
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: vault-ui
        path: ui-dist

  build-plugin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check git status
      run: git status
    - name: Build Plugin
      run: make build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: vault-auth-emerg-yubiotp
        path: pkg
    
  
  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: ["build-ui", "build-plugin"]
    steps:
    - name: Download UI
      uses: actions/download-artifact@v3
      with:
        name: vault-ui
        path: vault-ui
    - name: Tarball UI
      run: tar -czf vault-ui.tar.gz vault-ui && rm -rf vault-ui
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: vault-auth-emerg-yubiotp
    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          *
